# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  

  desc "Runs all the unit tests"
  lane :unit_test do
    gradle(task: "testDebugUnitTest")
  end

  

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Runing unit tests on Calculatrice class"
  lane :calculator_unit_tests do
    gradle(task: ":app:testDebugUnitTest --tests \"com.example.androidtestingapp.CalculatriceTest\"")
  end

  desc "Runing MainActivity UI tests"
  lane :main_ui_test do
    gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.androidtestingapp.MainActivityTest")
  end

  desc "Runing SecondActivity UI tests"
  lane :second_activity_ui_test do
    gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.androidtestingapp.MainActivityTest")
  end


  desc "Running continuous integration processes"
  lane : ci_process do
    unit_test
    main_ui_test
    second_activity_ui_test
  end







end


